{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "def test_1():\n        a = 1\n        b = 2\n        c = a + b\n        # 实际结果是3，预期结果是2\n        # 设定断言\n>       assert c == 2\nE       assert 3 == 2\n\ntest_1.py:13: AssertionError"}, "start": 1565593400018, "stop": 1565593400019, "uuid": "139da33a-563f-428c-8662-d03b38c59b18", "historyId": "3cad8cfacf91c8b31a8a3083c9e43271", "fullName": "test_1#test_1", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "10460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}