{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "def test_1():\n        a = 1\n        b = 2\n        c = a + b\n        # 实际结果是3，预期结果是2\n        # 设定断言\n>       assert c == 2\nE       assert 3 == 2\n\ntest_2.py:12: AssertionError"}, "start": 1565593400071, "stop": 1565593400071, "uuid": "abd03a16-ef21-4ec7-9388-5ee3aee0f36d", "historyId": "01f42bfb855075ccc2cf6e9cc2b48128", "fullName": "test_2#test_1", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "10460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2"}]}