{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "def test_1():\n        a = 1\n        b = 2\n        c = a + b\n        # 实际结果是3，预期结果是2\n        # 设定断言\n>       assert c == 2\nE       assert 3 == 2\n\nT1\\test_2.py:12: AssertionError"}, "start": 1565657740529, "stop": 1565657740530, "uuid": "a257ac9b-98cd-45c6-8c15-db0dc4c896ae", "historyId": "ef87de1afb52e13ce1eda10e8b6e797b", "fullName": "T1.test_2#test_1", "labels": [{"name": "parentSuite", "value": "T1"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite"}, {"name": "host", "value": "pc-guohonggang"}, {"name": "thread", "value": "11656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "T1.test_2"}]}